<?php

/*
	function omegaapaches_preprocess_page(&$variables) 
	{

		print_r(drupal_get_path('theme', 'omegaapaches')); 
		drupal_add_js(drupal_get_path('theme', 'omegaapaches') . '/js/jquery.mousewheel-3.0.6.pack.js');
		drupal_add_js(drupal_get_path('theme', 'omegaapaches') . '/js/fancybox/jquery.fancybox.pack.js');
		drupal_add_css(drupal_get_path('theme', 'omegaapaches') . '/js/fancybox/jquery.fancybox.css');
		
		$fancybox = "jQuery(document).ready(function() {
	 	   jQuery('.fancybox').fancybox();
		});";
		drupal_add_js($fancybox, 'inline');
	}
*/